feat: Add ComboBoxWrap
vaadin/testbench pull request #1402
Opened 2022-05-25 10:55 UTC by caalador

Part of #1371

2022-05-25 12:08 UTC, mcollovati requested changes

2022-05-25 12:08 UTC, mcollovati commented on vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/combobox/ComboBoxWrapTest.java
> +        final List<ComboBoxView.Name> suggestions = combo_.getSuggestionItems();
Shouldn't this test call `getSuggestion()`?

2022-05-25 12:08 UTC, mcollovati commented on vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/combobox/ComboBoxWrap.java
> +    public void selectItem(String selection) {
Is `null` a valid input for this method? Perhaps to clear current selection (if it is possible)?

2022-05-27 05:02 UTC, caalador commented on vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/combobox/ComboBoxView.java
> +    List<Name> items =Arrays.asList(new Name("foo"), new Name("bar"));
Formatted

2022-05-27 06:14 UTC, mcollovati approved these changes

2022-05-27 06:14 UTC, merged