feat: junit5 support for TestBench
vaadin/testbench pull request #1551
Opened 2022-10-14 06:57 UTC by MarcinVaadin

## Description

### Added `vaadin-testbench-core-junit5`
- Removed parallel scheduler in favor of native JUnit5 parallel support
- `DesiredCapabilities` features extracted to new package
- Multiple capabilities are now run using `TestTemplate` with `InvocationContextProvider`
- `Rules` converted to `Extensions`

### Added `vaadin-integration-tests-junit5` that are using new approach
- Prallel runs configured

### What needs to be done still:
- Implement `RetryRule` feature in JUnit5 way
### Migration notes:
- Update imports to `org.junit.jupiter.api.`
- Annotate test method with `@TestBenchTest` (name to be discussed) instead of `@Test`
- Extend `AbstractJUnit5TB6Test` instead of `AbstractTB6Test`

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-10-16 20:30 UTC, MarcinVaadin commented
Please don't care those dozens of pushes above - I was investigating the reason of CI tests flakiness...

2022-10-19 14:00 UTC, mshabarov requested changes
I haven't checked test and view classes, because I assume they are 99% copy-pasted from core module.

2022-10-19 14:03 UTC, mshabarov commented
Do you have, by the way, any tests/examples how can failsafe plugin be set up for retry on failures?

2022-10-19 18:38 UTC, MarcinVaadin commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/SetCapabilities.java
> +public interface SetCapabilities {
There is already org.openqa.selenium.HasCapabilities I need a name for interface with setter. Suggestion?

2022-10-19 18:38 UTC, MarcinVaadin commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/SetDriver.java
> +public interface SetDriver {
Yes, with empty `default` not to cause backward issues.

2022-10-19 18:40 UTC, MarcinVaadin commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/capabilities/CapabilitiesInvocationContextProvider.java
> +    private static class DesireCapabilitiesTestTemplateInvocationContext
Yes, it is possible to write custom `InvocationContextProvider` that will calculate custom displayName but will apply `CapabilitiesExtension` as it is already.

2022-10-19 19:00 UTC, MarcinVaadin commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/TestBenchUtil.java
> +public class TestBenchUtil
Done

2022-10-19 19:02 UTC, MarcinVaadin commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/TestBenchTestBase.java
> +public abstract class TestBenchTestBase implements HasDriver, SetDriver,
Javadoc copied from `TestBenchTestCase`

2022-10-19 21:48 UTC, MarcinVaadin commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/SetCapabilities.java
> +public interface SetCapabilities {
Removed in favor of ParameterResolver

2022-10-19 21:50 UTC, MarcinVaadin commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/SetDriver.java
> +public interface SetDriver {
Removed in favor of ParameterResolver

2022-10-20 05:58 UTC, mshabarov approved these changes

2022-10-20 05:58 UTC, mshabarov commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/TestBenchTest.java
> + * Shorthand annotation that combines {@code @TestTemplate} together with
```suggestion
 * Shorthand annotation for marking test methods in test class.
 * <p>
 * Combines JUnit 5 {@code @TestTemplate} together with
```

2022-10-20 05:58 UTC, mshabarov commented on vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/TestBenchTestBase.java
> + * A superclass with some helpers to aid TestBench developers.
```suggestion
 * A superclass with helper methods to aid TestBench developers create a JUnit 5 based tests.
```

2022-10-20 05:59 UTC, mshabarov commented
A couple of minor suggestions for javadoc, otherwise LGTM

2022-10-20 08:01 UTC, merged