Added tester for RouterLink.
vaadin/testbench pull request #1810
Opened 2024-07-08 21:58 UTC by joelpop

## Description

Adds missing `ComponentTester` for `RouterLink`. (Attempting to use `AnchorTester` in its place results in an error due to `Anchor` and `RouterLink` being different `Components`.

Tester methods include

- `getHref`
- `getPath`
- `getQueryParameters`
- `getRoute`
- `click`

Fixes #1805

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2024-08-05 14:15 UTC, mcollovati requested changes

2024-08-05 14:15 UTC, mcollovati commented on vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java
I would revert changes to this file that are not related to RouterLink

2024-08-05 14:15 UTC, mcollovati commented on vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/routerlink/RouterLinkTester.java
> +            throw new IllegalStateException();
This exception requires an explanatory message

2024-08-05 14:15 UTC, mcollovati commented on vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/routerlink/RouterLinkTester.java
> +    public Component click() {
What about returning `HasElement` to be consistent with `AnchorTester`?

2024-08-05 14:15 UTC, mcollovati commented on vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/routerlink/RouterLinkTester.java
> +    public Component click() {
The method should ensure that the component is usable by calling `ensureComponentIsUsable()`

2024-08-05 14:15 UTC, mcollovati commented on vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/RouterLinkTesterTest.java
> +                .single());
Same as for `RouterLink`, what about having the Span as a package protected field and simply assert on its `getText()`?

2025-02-11 08:42 UTC, mshabarov approved these changes

2025-02-11 08:42 UTC, mshabarov commented on vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java
> +    default <V> VirtualListTester<VirtualList<V>, V> test(VirtualList virtualList, Class<V> itemType) {
minor: 
`itemType` is not used, why we need this method? Maybe we shall deprecate?
This also needs the warning suppress, because of raw use of `VirtualList`.

2025-02-11 09:23 UTC, mcollovati commented on vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java
> +    default <V> VirtualListTester<VirtualList<V>, V> test(VirtualList virtualList, Class<V> itemType) {
The purpose of the parameter is to infer the correct generic type of the `VirualList` item.
If we remove it, the end user will be forced to cast the result in the test code, that is not nice.
The same pattern is applied for all generic components (e.g. `ComboBox`)

2025-02-11 09:28 UTC, mshabarov commented on vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java
> +    default <V> VirtualListTester<VirtualList<V>, V> test(VirtualList virtualList, Class<V> itemType) {
Ah, I see, thanks, it's needed for `VirtualListTester<VirtualList<V>, V>` despite it's not directly used in the method's body.

2025-02-11 09:29 UTC, merged